In [672]:
import torch 
print(torch.__version__)

2.1.2+cpu


## Introductioin to Tensors

### creating Tensore
PyTorch tensors are created using `torch.Tensor() -= https://pytorch.org/docs/stable.tensor.html `

In [673]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [674]:
scalar.ndim

0

In [675]:
#get tensor back as integer
scalar.item()

7

In [676]:
#Vector
vector= torch.tensor([7,7])
vector

tensor([7, 7])

In [677]:
vector.ndim

1

In [678]:
vector.shape

torch.Size([2])

In [679]:
# Matrix 
matrix= torch.tensor([[7,7], [8,8]])

matrix

tensor([[7, 7],
        [8, 8]])

In [680]:
matrix.ndim

2

In [681]:
matrix.shape

torch.Size([2, 2])

In [682]:
# Tensors

TENSOR= torch.tensor([[[1,2,3], [3,6,9], [90,86,57]]])

TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [90, 86, 57]]])

In [683]:
TENSOR.ndim, TENSOR.shape

(3, torch.Size([1, 3, 3]))

In [684]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 3,  6,  9],
        [90, 86, 57]])

## Tut 2
### Random Tensors
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [685]:
## Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4857, 0.6827, 0.3312, 0.7261],
        [0.9307, 0.1720, 0.2876, 0.0489],
        [0.2171, 0.0854, 0.6454, 0.1071]])

In [686]:
# Create a random tensor with similar shape to an image tensor

image_size_tensor= torch.rand(size= (244, 244,3)) # height, width, color channels

image_size_tensor.shape , image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

## Tutorial 3

Zeros and Ones

In [687]:
zeros= torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [688]:
ones= torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Range of tensors and tensors-like

In [689]:
## use torch.range()

one_to_ten= torch.arange(start= 0,end= 1000 , step= 77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [690]:
# creating tensors-like

ten_zeros= torch.zeros_like(input= one_to_ten ) 
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatype

In [691]:
# float 32 torch

float_32_tensor= torch.tensor([3, 6, 9],
                              dtype=torch.float32, # what daratype is the tensor
                              device= "cpu", # What device is your tensor on 
                              requires_grad=False) # whether or not to track gradients with this tensors operation 
float_32_tensor

tensor([3., 6., 9.])

In [692]:
float_32_tensor.dtype

torch.float32

In [693]:
float_16_tensor= float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [694]:
float_32_tensor*float_16_tensor

tensor([ 9., 36., 81.])

In [695]:
## find details about some tensor 
some_tensor= torch.rand(3,4)
some_tensor

tensor([[0.6569, 0.1814, 0.4987, 0.9940],
        [0.4732, 0.2480, 0.0497, 0.3257],
        [0.7362, 0.6454, 0.5011, 0.2749]])

In [696]:
print(some_tensor)
print(f"Datatype= {some_tensor.dtype} \nShape of Tensor= {some_tensor.shape} \nDevice tensor is on= {some_tensor.device}")

tensor([[0.6569, 0.1814, 0.4987, 0.9940],
        [0.4732, 0.2480, 0.0497, 0.3257],
        [0.7362, 0.6454, 0.5011, 0.2749]])
Datatype= torch.float32 
Shape of Tensor= torch.Size([3, 4]) 
Device tensor is on= cpu


### ~Manupulating Tensors~

# tensor operations
Tensor operation include:

* addition 
* subtraction
* division
* matrix multiplication

In [697]:
tensor = torch.tensor([1 , 2 , 3])

tensor + 10

tensor([11, 12, 13])

In [698]:
tensor*=10
tensor

tensor([10, 20, 30])

### Matrix Multipication

In [699]:
one= torch.rand(4,4)
two= torch.rand(4,9)

one,two

(tensor([[0.2876, 0.0319, 0.1314, 0.3533],
         [0.3468, 0.7314, 0.8853, 0.6458],
         [0.7585, 0.7235, 0.9562, 0.0191],
         [0.5594, 0.0416, 0.6011, 0.5742]]),
 tensor([[0.7502, 0.1297, 0.3613, 0.5730, 0.9173, 0.1070, 0.1285, 0.9772, 0.3775],
         [0.1664, 0.4026, 0.9007, 0.0844, 0.7249, 0.1459, 0.0941, 0.8467, 0.9185],
         [0.1212, 0.1779, 0.1531, 0.3827, 0.9054, 0.6717, 0.4775, 0.4168, 0.0746],
         [0.6854, 0.7190, 0.4350, 0.6819, 0.4236, 0.6462, 0.9893, 0.1827, 0.5834]]))

In [700]:
torch.matmul(one,two)

tensor([[0.4791, 0.3275, 0.3064, 0.4587, 0.5556, 0.3520, 0.4522, 0.4274, 0.3538],
        [0.9318, 0.9613, 1.2005, 1.0396, 1.9234, 1.1558, 1.1751, 1.4451, 1.2455],
        [0.8183, 0.5735, 1.0804, 0.8746, 2.0941, 0.8413, 0.6410, 1.7558, 1.0334],
        [0.8929, 0.6091, 0.5814, 0.9456, 1.3307, 0.8407, 0.9309, 0.9372, 0.6292]])

In [701]:
one @ two

tensor([[0.4791, 0.3275, 0.3064, 0.4587, 0.5556, 0.3520, 0.4522, 0.4274, 0.3538],
        [0.9318, 0.9613, 1.2005, 1.0396, 1.9234, 1.1558, 1.1751, 1.4451, 1.2455],
        [0.8183, 0.5735, 1.0804, 0.8746, 2.0941, 0.8413, 0.6410, 1.7558, 1.0334],
        [0.8929, 0.6091, 0.5814, 0.9456, 1.3307, 0.8407, 0.9309, 0.9372, 0.6292]])

In [705]:
## to fix tensor issues , we can use transpose property

one.T @ two, one.T

(tensor([[0.7488, 0.7141, 0.7757, 0.8658, 1.4389, 0.9523, 0.9852, 0.9930, 0.8101],
         [0.2618, 0.4572, 0.7991, 0.3852, 1.2321, 0.6230, 0.4596, 0.9595, 0.7621],
         [0.7737, 0.9757, 1.2527, 0.9258, 1.8826, 1.1739, 1.1515, 1.3863, 1.2848],
         [0.7684, 0.7220, 0.9620, 0.6558, 1.0527, 0.5159, 0.6833, 1.0049, 1.0629]]),
 tensor([[0.2876, 0.3468, 0.7585, 0.5594],
         [0.0319, 0.7314, 0.7235, 0.0416],
         [0.1314, 0.8853, 0.9562, 0.6011],
         [0.3533, 0.6458, 0.0191, 0.5742]]))

### Finding Tensor Aggregation

In [706]:
## create a tensor
x= torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [708]:
# find the min and max

torch.min(x), x.min(), torch.max(x), x.max()

(tensor(0), tensor(0), tensor(90), tensor(90))

In [ ]:
# find mean 